---

# Important Notes:
#
# 1. The config under `.products.<PRODUCT_ALIAS>` must be compatible with `download-product` config file.
#    Ref: http://docs.pivotal.io/platform-automation/v3.0/reference/inputs-outputs.html#download-product-config
# 2. For OpsMan, we must not set `stemcell-iaas`
# 3. For products, there are two options:
#    - If one simply sets `stemcell-iaas: <iaas>`, it would retrieve the latest version of stemcell among the applicable range
#    - If one desires a full control on which stemcell you want to use, specify the `<PRODUCT_ALIAS>-stemcell` session
# 4. The options available for `stemcell-iaas`: vsphere; vcloud; openstack; google; azure; aws
#

products:

  # ==== Ops Manager
  opsman:
    product-version: "2.6.9"
    pivnet-product-slug: ops-manager
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "ops-manager-gcp-*.yml"

  # ==== Products

  # PAS
  pas:
    product-version: "2.6.5"
    pivnet-product-slug: elastic-runtime
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "srt-*.pivotal"            # For full fledged PAS, use "cf-*.pivotal"
    stemcell-iaas: google                        # 1) uncomment it if one desires the latest applicable stemcell for the product, or
  #pas-stemcell:                                 # 2) use this session to specify exact stemcell you want
  #  product-version: "315.99"                   # applicable stemcell range: 315.93–315.99
  #  pivnet-product-slug: stemcells-ubuntu-xenial
  #  pivnet-api-token: ((pivnet_token))
  #  pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  # CSB
  csb:
    product-version: "1.4.1"
    pivnet-product-slug: credhub-service-broker
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: google                        # 1) uncomment it if one desires the latest applicable stemcell for the product, or
  #csb-stemcell:                                 # 2) use this session to specify exact stemcell you want
  #  product-version: "315.89"                   # applicable stemcell range: 315.*
  #  pivnet-product-slug: stemcells-ubuntu-xenial
  #  pivnet-api-token: ((pivnet_token))
  #  pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"

  # Redis
  redis:
    product-version: "2.2.1"
    pivnet-product-slug: p-redis
    pivnet-api-token: ((pivnet_token))
    pivnet-file-glob: "*.pivotal"
    stemcell-iaas: google                        # 1) uncomment it if one desires the latest applicable stemcell for the product, or
  #redis-stemcell:                               # 2) use this session to specify exact stemcell you want
  #  product-version: "315.89"                   # applicable stemcell range: 315.*
  #  pivnet-product-slug: stemcells-ubuntu-xenial
  #  pivnet-api-token: ((pivnet_token))
  #  pivnet-file-glob: "light-bosh-stemcell-*-google-kvm-ubuntu-xenial-go_agent.tgz"
